name: Update new data

on:
  schedule:
    - cron: "10 14 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download data
      run: wget -O data/data-`date +%Y-%m-%d`.json https://citymapper.com/api/gobot_tab/data
    - name: Run main
      run: python main.py
    - name: Push to data.gouv.fr
      run: |
        curl -H "Accept:application/json" \
          -H "X-Api-Key:$DATA_GOUV_API_KEY" \
          -F "file=@data.csv" \
          -X POST $API/datasets/$DATASET_ID/resources/$RESOURCE/upload/
      env:
        DATA_GOUV_API_KEY: ${{ secrets.DATA_GOUV_API_KEY }}
        API: "https://www.data.gouv.fr/api/1"
        DATASET_ID: "5e7ca7511bc790fc68223a2f"
        RESOURCE: "0e56f0f4-6a82-48d4-b677-96e950100176"
    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git commit -am "Add daily data"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
